### ISSUE TITLE
Correção do titulo da sessão Sobre Mim

### ISSUE THREAD

**Issue by YuriSouzaDev** [sspacecoding/curriculodasguria#1]
Olá, Giulia

Parabéns por mais um Deploy na Sexta excepcional.

Queria adicionar uma correção na disposição do titulo do Sobre Mim que estava pegando o texto justificado do texto logo abaixo.

Separei eles e coloquei um pequeno espaçamento entre eles para dar o espaçamento idêntico para não alterar mais nada.

E mais uma vez parabens pelo o projeto como um todo.

[Modelo de Currículo traduzido do Artur Khalatian CV.docx](https://github.com/sspacecoding/curriculodasguria/files/14062866/Modelo.de.Curriculo.traduzido.do.Artur.Khalatian.CV.docx)

**Comment by sspacecoding** [comment]
Muito obrigada pela contribuição, vou substituir no arquivo 💙
